name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk
        pip install buildozer
        
    - name: Build APK
      run: |
        buildozer -v android release
        cp bin/*.apk .
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: videoparser-apk
        path: |
          *.apk
